db:
  image: postgres
  env_file:
    - ./env_dev

web:
  build: .
  command: bash -c "sleep 7 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # waiting for psql init completed db in first time
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
  env_file:
    - ./env_dev